; This file is for the FamiTone2 library and was generated by FamiStudio

_hit_sfx:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_song_1

@sfx_ntsc_song_1:
	.byte $84,$74,$85,$04,$83,$3f,$89,$f0,$03,$00

.export _hit_sfx
