; This file is for the FamiTone2 library and was generated by FamiStudio
_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export _music_data
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $30 ; 00 : Instrument 1
	.word @env0, @env1, @env1
	.byte $00

@env0:
	.byte $cf,$7f,$00,$00
@env1:
	.byte $c0,$7f,$00,$01

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $80
@song0ref5:
	.byte $44, $8b, $00, $8b, $44, $8b, $00, $8b, $4a, $8b, $00, $8b, $44, $8b, $00, $8b, $4e, $8b, $00, $8b, $44, $8b, $00, $8b
	.byte $52, $8b, $00, $8b, $4e, $8b, $00, $8b, $4a, $8b, $00, $8b, $4a, $8b, $00, $8b, $52, $8b, $00, $8b, $4a, $8b, $00, $8b
	.byte $58, $8b, $00, $8b, $4a, $8b, $00, $8b, $52, $8b, $00, $8b, $4a, $8b, $00, $8b
@song0ref69:
	.byte $40, $8b, $00, $8b, $40, $8b, $00, $8b, $48, $8b, $00, $8b, $40, $8b, $00, $8b, $4a, $8b, $00, $8b, $40, $8b, $00, $8b
	.byte $4e, $8b, $00, $8b, $4a, $8b, $00, $8b, $3c, $8b, $00, $8b, $3c, $8b, $00, $8b, $44, $8b, $00, $8b, $3c, $8b, $00, $8b
	.byte $4a, $8b, $00, $8b, $3c, $8b, $00, $8b, $4a, $8b, $00, $8b, $48, $8b, $00, $8b
	.byte $ff, $80
	.word @song0ref5
	.byte $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5
@song0ref144:
	.byte $5c, $8b, $00, $99, $5c, $8b, $00, $99, $5c, $8b, $00, $99, $5c, $8b, $00, $99, $58, $8b, $00, $8b, $62, $8b, $62, $8b
	.byte $5c, $8b, $00, $99, $5c, $8b, $00, $99, $5c, $8b, $00, $99, $5c, $8b, $00, $99, $58, $8b, $00, $8b, $52, $8b, $52, $8b
	.byte $ff, $30
	.word @song0ref144
	.byte $ff, $30
	.word @song0ref144
	.byte $ff, $30
	.word @song0ref144
	.byte $ff, $30
	.word @song0ref144
	.byte $ff, $30
	.word @song0ref144
	.byte $00, $f9, $e3, $f9, $e5, $f9, $e5, $f9, $e5
	.byte $ff, $40
	.word @song0ref69
	.byte $f9, $e5, $f9, $e5, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $80
@song0ref244:
	.byte $44, $8b, $00, $99, $44, $8b, $00, $99, $44, $8b, $00, $99, $44, $8b, $00, $99, $40, $8b, $00, $8b, $4a, $8b, $4a, $8b
	.byte $44, $8b, $00, $99, $44, $8b, $00, $99, $44, $8b, $00, $99, $44, $8b, $00, $99, $40, $8b, $00, $8b, $3a, $8b, $3a, $8b
	.byte $ff, $23
	.word @song0ref244
	.byte $8b, $44, $85, $00, $83, $44, $85, $00, $91, $44, $85, $00, $83, $44, $85, $00, $ad
	.byte $ff, $30
	.word @song0ref244
	.byte $ff, $30
	.word @song0ref244
	.byte $ff, $30
	.word @song0ref244
	.byte $ff, $30
	.word @song0ref244
	.byte $ff, $30
	.word @song0ref244
	.byte $ff, $30
	.word @song0ref244
	.byte $00, $f9, $e3, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $80
@song0ref360:
	.byte $44, $8b, $00, $8b, $44, $8b, $00, $8b, $44, $8b, $00, $8b, $40, $8b, $00, $8b, $44, $8b, $00, $8b, $44, $8b, $00, $8b
	.byte $44, $8b, $00, $8b, $40, $8b, $00, $8b
	.byte $ff, $20
	.word @song0ref360
	.byte $ff, $20
	.word @song0ref360
	.byte $ff, $20
	.word @song0ref360
@song0ref401:
	.byte $44, $8b, $00, $99, $44, $8b, $00, $99, $44, $8b, $00, $8b, $44, $8b, $00, $8b, $44, $8b, $00, $8b, $40, $8b, $00, $8b
	.byte $4a, $8b, $00, $8b, $44, $8b, $00, $99, $44, $8b, $00, $99, $44, $8b, $00, $8b, $44, $8b, $00, $8b, $44, $8b, $00, $8b
	.byte $40, $8b, $00, $8d, $3a, $8b, $00, $89
	.byte $ff, $27
	.word @song0ref401
	.byte $99, $44, $8b, $00, $85, $44, $87, $00, $87, $44, $8b, $00, $a7
	.byte $ff, $38
	.word @song0ref401
	.byte $ff, $38
	.word @song0ref401
	.byte $ff, $38
	.word @song0ref401
	.byte $ff, $38
	.word @song0ref401
	.byte $ff, $38
	.word @song0ref401
	.byte $ff, $38
	.word @song0ref401
	.byte $ff, $20
	.word @song0ref360
	.byte $ff, $20
	.word @song0ref360
	.byte $ff, $20
	.word @song0ref360
	.byte $ff, $20
	.word @song0ref360
	.byte $ff, $20
	.word @song0ref360
	.byte $ff, $20
	.word @song0ref360
	.byte $ff, $20
	.word @song0ref360
	.byte $ff, $20
	.word @song0ref360
	.byte $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref519:
	.byte $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5
	.byte $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5
	.byte $ff, $20
	.word @song0ref519
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $20
	.word @song0ref519
	.byte $ff, $20
	.word @song0ref519
	.byte $fd
	.word @song0ch4loop
